name: C++ CI Workflow with conda-forge dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "weekly" build at 2 AM UTC on Sunday
  - cron:  '0 2 * * 0'

jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}@conda]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-2019, macOS-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        miniforge-variant: Mambaforge

    - name: Dependencies
      shell: bash -l {0}
      run: |
        # Workaround for https://github.com/conda-incubator/setup-miniconda/issues/186
        conda config --remove channels defaults
        mamba install cmake compilers make ninja pkg-config ycm-cmake-modules

    - name: Additional Dependencies [Windows]
      if: contains(matrix.os, 'windows')
      shell: bash -l {0}
      run: |
        mamba install vs2019_win-64


    - name: Configure [Linux&macOS]
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

    - name: Build 
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}
        
    - name: Install
      run: |
        cd build
        cmake --install . --config ${{ matrix.build_type }}
